#!/bin/sh

cd /home/mel/var/mail/spam

touch .depourrir.cePassage

if [ -f .depourrir.dernierPassage ]
then
	optionsFind="-newer .depourrir.dernierPassage"
else
	#optionsFind="-mtime -100"
fi

pourris()
{
	find ../*/*/cur/ -type f $optionsFind -print0 | xargs -0 egrep -a '^(D....|.KIM-)Signature:|^DKIM-' | grep -av DKIM-Signature: | grep -av Dkim-Signature: | grep -av DKIM-Filter: | cut -d : -f 1-2
}

for f in `pourris`
do
	pourri "$f"
done

mv .depourrir.cePassage .depourrir.dernierPassage
