#!/bin/sh

n=40
case "$1" in *[^0-9]*) true ;; [1-9]*) n=$1 ; shift ;; esac

t=/tmp/temp.lchopes.$$

ls -tr | egrep -v 'bz2$|gz$' | tail -$n > $t.fichiers

tr '\012' '\000' < $t.fichiers | xargs -0 -n 10 rspamc "$@" | LC_ALL=C stdbuf -oL awk '/^Results for file:/{f=$4}/^Score:/{p=$2;printf("%s%.2f%s %s\n", (p>=18.0?"\033[32m":(p>=15.0?"\033[33m":"\033[31m")), p, "\033[0m\t", f)}' > $t.resultats &

att=30
while read f
do
	while [ "$att" -gt 0 ] && ! grep -q -F "$f" < $t.resultats
	do
		att=`expr $att - 1`
		sleep 1
	done
	if ! grep -q -F "$f" < $t.resultats
	then
		printf "%s\t???\n" "$f"
		att=5
		continue
	else
		att=30
	fi
	grep -F "$f" < $t.resultats | while read n f
	do
		printf "%s\t" "$n"
		ls -l "$f" | awk '{printf("%s\t%s\t%s\t%s\t%s\t",$5,$6,$7,$8,$9)}'
		awk 'oui&&!/^[ \t]|^$/{print oui;exit}/^$/{exit}oui{oui=oui""substr($0,2)}/^Subject: /{oui=substr($0,10)}END{if(!oui)print"---"}' < "$f"
	done
done < $t.fichiers | /tmp/tmp/src/scripts/texte/derfc822

rm -f $t.*

# Pour faire la part des choses:
# lchopes
# fs="<fichier 1 potentiel faux positif> <fichier 2> <etc.>"
# for f in $fs ; do rspamc $f ; grep ^From "$f" ; done | egrep '^Results|^Score|^From|G_PAF' | sed -e 's/ ([^ ]* seconds)//' > /tmp/1
# # Bidouiller dans les règles
# # Relancer le for pour voir si les choses ont évolué.
