#!/bin/sh

# À FAIRE: passer par gogo pour ne pas atomiser rspamd (pas + de 5 à la fois), sinon il expire je ne sais quel délai et ne renvoie aucun résultat pour les derniers.
n=12
[ -z "$1" ] || n="$1"

t=/tmp/temp.lpasses.$$

ls -tr `for i in ../*/*/.Spam/cur/ ../*/*/.Poubelle/cur/ ; do ls -tr "$i" | tail -$n | sed -e "s#^#$i#" ; done` | tail -$n > $t.fichiers

tr '\012' '\000' < $t.fichiers | xargs -0 rspamc | LC_ALL=C awk '/^Results for file:/{f=$4}/^Score:/{p=$2;print (p>=18.0?"\033[32m":(p>=15.0?"\033[33m":"\033[31m"))p"\033[0m\t"f}' > $t.resultats &

for i in a b c ; do [ -f "$t.resultats" ] && break ; sleep 1 ; done
while read f
do
	while ! grep -q -F "$f" < $t.resultats
	do
		sleep 1
	done
	grep -F "$f" < $t.resultats
done < $t.fichiers

rm -f $t.*
