#!/bin/sh

ssh -o ConnectTimeout=3 mb true > /dev/null 2>&1
injoignable=$?
# À FAIRE: comment avoir la puissance du signal? txpower ne semble pas varier, sysctl net.wlan ne renvoie rien d'intéressant.
ifconfig | awk '
function aff() {
	if(!interf || interf ~ /^lo/) return;
	printf("%s <span foreground=\"%s\">%s</span> %s %s", (interf ~ "^wlan" ? "🛜" : "🖧"), (etat == "associated" ? ('"$injoignable"' ? "orange" : "green") : "red"), interf, reseau, puiss);
}
/^[^\t]/{
	aff();
	interf = $1;
	sub(/:/, "", interf);
	sub(/^[^:]*: /, "\t");
	puiss = etat = reseau = "";
	if($0 ~ /<UP,/) etat = "associated"; # Une interface filaire UP c est comme un sans fil associated.
}
{
	for(i = 0; ++i <= NF;)
		if($i == "ssid")
			reseau = $++i;
		else if($i == "status:")
			etat = $++i;
		else if($i == "txpower")
			puiss = $++i;
}
END{ aff(); }
'

