#!/bin/sh

# Bascule le réseau sur ue0 (Ethernet over USB), FreeBSD 15 se montrant incapable de se connecter dans des environnements saturés (ex.: chez ACTE, perdu entre tous les WiFi, il se montre incapable d'en accrocher aucun, pas même mon partage de connexion téléphone lorsqu'elle est active).

# À FAIRE: arret()
# À FAIRE: le lancer en auto quand on détecte une interface ue0, l'arrêter quand elle disparaît

marche()
{
	case "$1" in -) bascule ; return ;; esac # ./usb - # Bascule sur le wlan même si l'USB (de secours) est encore debout.
	
	case $# in 0) # Si on nous appelle avec un --essaie-quand-même-d-accrocher-un-réseau, on laisse tourner le wpa_supplicant en tâche de fond.
	sudo service wpa_supplicant stop wlan0
	;; esac
	sudo route delete default
	sudo service dhclient start ue0
}

# Rebascule sur le Wi-Fi après un passage en usb + (usb le temps d'accrocher le Wi-Fi).
# À FAIRE: détecter quand on peut basculer en WiFi
bascule()
{
	sudo ifconfig ue0 down
	sudo resolvconf -d ue0
	# À FAIRE: ne marche pas terrible (perd le ssid). pê ajouter des sleep 1?
	sudo route delete default
	sudo service dhclient restart wlan0
}

arret()
{
	sudo resolvconf -d ue0
	sudo service wpa_supplicant start wlan0
}

if ifconfig ue0 > /dev/null 2>&1
then
	marche "$@"
else
	arret
fi
