#!/bin/bash

une()
{
	[ -z "$d" ] || ~gui/src/scripts/sauvegarde/lner "$1" "$d"
	d="$1"
}

if [ $# -gt 0 ]
then
	i=$#
	declare -a t
	for n in "$@"
	do
		t[$((--i))]="$n"
	done
	for n in "${t[@]}" ; do une "$n" ; done
else
ls -d panoramix.200* | rev | while read n ; do une "$n" ; done
fi
