#!/bin/sh

dests=
for dest in \
	ssh://b/Documents/partage \
	ssh://mdm/Documents/partage \
	ssh://partage/sauvegardes/partage
do
	dests="$dests$dest "
done

for dest in $dests
do
	lockf -t 10 $HOME/tmp/partage.verrou $HOME/local/bin/unison -batch -backups -maxbackups 3 $HOME/partage $dest
done
