#!/bin/sh

GOGO_SCRIPTS="$HOME/src/projets/gogo"
. "$GOGO_SCRIPTS/gogo.sh" # gogo >= 0.8

tourner()
{
	source=
dests=
	hote=`hostname | tr A-Z a-z | cut -d . -f 1`
for dest in \
	ssh://p/partage \
	ssh://b/Documents/partage \
	ssh://mdm/Documents/partage \
	ssh://partage/sauvegardes/partage
do
	case "$hote:$dest" in
			pasdfric:ssh://p/*) true ;;
			bonemine:ssh://b/*) true ;;
			muxdemux:ssh://mdm/*) true ;;
			sauvegardes:ssh://partage/*) true ;;
			*)
	dests="$dests$dest "
				continue
				;;
		esac
		source="$HOME/`echo "$dest" | cut -d / -f 4-`"
done
	case "$source" in "")
		echo "[31m# Impossible de déterminer qui je suis parmi la liste préprogrammée.[0m" >&2
		exit 1
	;; esac

	gogo_dance
}

gogogo()
{
	local dest num=0
	
	Lance lancement: true # Une première tâche nommée "lancement" pour que celles lancées dans notre boucle puissent faire un Apres lancement~ sans message d'erreur "je suis la première de la lignée, donc il n'y en a aucune de ce nom".
	
	for dest in $dests
	do
		Lance joindreEtPlanifier $num "$dest"
		num=$((num + 1))
	done
}

joindreEtPlanifier()
{
	local num=$1 dest="$2" h="`echo "$2" | sed -e 's#.*://##' -e 's#/.*##'`"
	local file joignable=$(ssh -o ConnectTimeout=5 "$h" sh -c 'ps auxww | grep "[u]nison" | wc -l' | tr -d ' \t')
	case "$joignable" in
		"") return 0 ;;
		0) true ;;
		*) sleep 1 ;; # Une façon de temporiser le lancement si un unison tourne déjà. En réalité on temporise l'empilement via Après, ce qui nous empilera après tous ceux déjà empilés sous ce nom (et la seconde supplémentaire laisse un peu plus de temps pour détecter d'autres qui peuvent être lancés immédiatement).
	esac
	echo "$h joignable, $joignable unison tournant déjà dessus"
	Apres lancement~ lancement: faire "$h" "$dest"
}

faire()
{
	local dest="$2"
	echo "Je fais $1"
	lockf -t 10 $HOME/tmp/partage.verrou $HOME/local/bin/unison -batch -backups -maxbackups 3 $source $dest
}

case `uname` in
	Linux)
		lockf()
		{
			case "$1" in -t) shift ; set -- -w "$@" ;; esac
			flock "$@"
		}
		;;
esac

tourner "$@"
