#!/bin/sh

# Accélération des Requêtes de Résolution par Anticipation Consignée dans le Hosts
# Correction du Hosts pour Écourter les Futures Sollicitations
# Requête d'Actualisation des Paramètres Hosts

# Cache le résultat d'une requête DNS dans le resolv.conf

ip()
{
	drill "$1" | sed -e '/.*	A	\([0-9a-f]\)/!d' -e 's//\1/' | head -1
}

faire()
{
	local h ip expr sed ajouts
	for h in "$@"
	do
		ip="`ip "$h"`"
		[ -n "$ip" ] || continue
		expr="	$h$"
		sed="$sed -e /$expr/s/.*/$ip	$h/"
		grep -q "$expr" < /etc/hosts || ajouts="$ajouts+0.0.0.0	$h"
	done
	[ -n "$sed" ] || return
	sed="sed$sed"
	IFS=" "
	(
		cat /etc/hosts
		[ -z "$ajouts" ] || echo "$ajouts" | tr + '\012'
	) |	$sed > /tmp/hosts && sudo sh -c 'cat > /etc/hosts' < /tmp/hosts
}

faire "$@"
