#!/bin/bash

auSecours()
{
	nom=`basename "$0"`
	cat >&2 << TERMINE
# $nom
# Réémission de message
# © 2006 Guillaume Outters

Utilisation: $nom [-][<nom> <adrél>]*
  <nom>                         nom de la personne.
  <adrél>                       adresse du destinataire.
  -                             les adresses après le - apparaîtront dans le
                                To:, mais ne recevront pas le mél.
Le message doit être fourni sur l'entrée standard.
TERMINE
	exit 1
}

declare -a personnes adresses
analyserParametres()
{
	stop=0
	serveur=smtp.free.fr
	port=25
	while [ $# -gt 0 ] ; do
		case "$1" in
			-h|--help) auSecours ;;
			-) stop=1 ;;
			-s) shift ; [[ "$1" = *:* ]] && port="${1##*:}" ; serveur="${1%%:*}" ;;
			*)
				if [ "${#personnes[@]}" -eq "${#adresses[@]}" ]
				then
					personnes[${#personnes[@]}]="$1"
				else
					adresses[${#adresses[@]}]="$1"
					[ $stop = 0 ] && destinataires[${#destinataires[@]}]="$1"
				fi
				;;
		esac
		shift
	done
}

analyserParametres "$@"

[ "${#destinataires[@]}" -lt 1 ] && auSecours

n=${#adresses[@]}
while [ $((--n)) -ge 0 ]
do
personnes[$n]="`
python << TERMINE
# -*- coding: utf-8 -*-
import locale
from email.Header import Header
print Header('${personnes[n]//\'/\'}'.decode(locale.getdefaultlocale()[1]), 'iso-8859-1').encode()
TERMINE
`"
done

( echo EHLO 82.240.30.31 ; sleep 1 ; echo "MAIL FROM: <guillaume.outters@free.fr>" ; sleep 1 ; for adresse in ${destinataires[@]} ; do echo "RCPT TO: <$adresse>" ; sleep 1 ; done ; echo DATA ; sleep 1 ; awk '{if(corps){print;next}}/^$/{corps=1}/^  /{if(!vire)print;next}{vire=0}/^Delivered-To: /{vire=1}/^To: /{print "To: '"`n=${#adresses[@]} ; while [ $((--n)) -ge 0 ] ; do echo -n "${personnes[$n]} <${adresses[$n]}>,\\n  " ; done`"'"substr($0,5);next}{if(!vire)print}' ; sleep 1 ; echo . ; sleep 1 ; echo QUIT ; sleep 1 ) | nc $serveur $port
# while [ `date +%Y%m%d%H%M | cut -c 7-` -lt 190001 ] ; do sleep 10 ; done ; ( sleep 1 ; echo EHLO 89.88.76.4 ; sleep 1 ; echo AUTH LOGIN ; sleep 1 ; echo Z3VpbGxhdW1lLm91dHRlcnM= ; sleep 1 ; echo cG9pcmVhdQ== ; sleep 1 ; echo MAIL FROM: guillaume.outters@free.fr ; sleep 1 ; echo RCPT TO: outtersg@yahoo.fr ; sleep 1 ; echo RCPT TO: alixdenoray@yahoo.fr ; sleep 1 ; echo DATA ; sleep 1 ; sed -e '1d' -e '/^</,$d' -e 's/<.xml.*//' < 105597.emlx ; sleep 1 ; echo . ; sleep 1 ; echo QUIT ; sleep 1 ) | telnet 212.27.48.4 587
