#!/bin/bash

auSecours()
{
	nom=`basename "$0"`
	cat >&2 << TERMINE
# $nom
# Réémission de message
# © 2006 Guillaume Outters

Utilisation: $nom <nom> <adrél>
  <nom>                         nom de la personne. Attention, le programme ne
                                gère pas encore les caractères accentués!
  <adrél>                       adresse du destinataire.
Le message doit être fourni sur l'entrée standard.
TERMINE
	exit 1
}

declare -a personnes adresses
analyserParametres()
{
	while [ $# -gt 0 ] ; do
		case "$1" in
			-h|--help) auSecours ;;
			*)
				if [ "${#personnes[@]}" -eq "${#adresses[@]}" ]
				then
					personnes[${#personnes[@]}]="$1"
				else
					adresses[${#adresses[@]}]="$1"
				fi
				;;
		esac
		shift
	done
}

analyserParametres "$@"

[ "${#adresses[@]}" -lt 1 ] && auSecours

n=${#adresses[@]}
while [ $((--n)) -ge 0 ]
do
personnes[$n]="`
python << TERMINE
# -*- coding: utf-8 -*-
import locale
from email.Header import Header
print Header('${personnes[n]}'.decode(locale.getdefaultlocale()[1]), 'iso-8859-1').encode()
TERMINE
`"
done

( echo EHLO 82.240.30.31 ; sleep 1 ; echo "MAIL FROM: <guillaume.outters@free.fr>" ; sleep 1 ; for adresse in ${adresses[@]} ; do echo "RCPT TO: <$adresse>" ; sleep 1 ; done ; echo DATA ; sleep 1 ; awk '{if(corps){print;next}}/^$/{corps=1}/^  /{if(!vire)print;next}{vire=0}/^Delivered-To: /{vire=1}/^To: /{print "To: '"`n=${#adresses[@]} ; while [ $((--n)) -ge 0 ] ; do echo -n "${personnes[$n]} <${adresses[$n]}>,\\n  " ; done`"'"substr($0,5);next}{if(!vire)print}' ; sleep 1 ; echo . ; sleep 1 ; echo QUIT ; sleep 1 ) | nc smtp.free.fr smtp
