#!/bin/sh

moiGitHub=outtersg
racineComposer=gui
moiComposer="Guillaume Outters"

set -e

err()
{
	echo "$*" >&2
	exit 1
}

daterVersionComposer()
{
	if [ -f composer.json ] && egrep -q '"version": "[0-9]*\.[0-9]*([0-9.]*|\.x-dev)"' < composer.json
	then
		dateDernier="`darcs changes --last 1 --xml | sed -e '/ date=/!d' -e 's/.* date=//' -e 's/ .*//' | head -1 | tr -d \''"'`"
		case "$dateDernier" in
			20????????????)
				jourDernier="`echo "$dateDernier" | cut -c 1-8`"
				heureDernier="`echo "$dateDernier" | cut -c 9-`"
				jourDernierMoins2000="`expr "$jourDernier" - 20000000`"
				;;
		esac
		sed -E -e 's#("version": *"[0-9]+\.[0-9]+).*"#\1.'"$jourDernierMoins2000"'"#g' < composer.json > composer2.json && mv composer2.json composer.json
		if false
		then
			local auteur="`[ -f _darcs/prefs/author ] && cat _darcs/prefs/author || darcs changes --last=1 | grep ^Author: | cut -d ' ' -f 2-`"
			( echo $dateDernier ; echo "$auteur" ; echo "composer.json: date du jour" ; echo "= Comme les œufs." ) | LANG=fr_FR.UTF-8 LC_ALL=fr_FR.UTF-8 darcs record --pipe -a composer.json
		else
			v="`sed < composer.json -e '/.*"version" *: *"\([0-9.]*\)".*/!d' -e 's//\1/'`"
			if git tag | grep -q "$v"
			then
				true
			else
				git branch "$v"
				git checkout "$v"
				git commit -m "composer.json: date du jour" composer.json
				git tag "$v"
				git checkout master
				git branch -D "$v"
			fi
		fi
	fi
}

[ -d _darcs ] || err "Vous devez vous trouver dans un dossier racine darcsisé (_darcs doit exister)."

[ -e .git/index ] && err ".git contient déjà un dossier git. Je ne peux travailler dessus."

d2g="`command -v darcs-to-git`"
[ 2 -eq "`grep Ignore-this: < "$d2g" | wc -l`" ] || err "Veuillez utiliser une version de darcs-to-git qui vire les Ignore-this:"

nom="`basename "$PWD"`"
PACKAGIST_API_TOKEN=xxxxxxxxxxxxxxxxxxxx

if [ ! -d .git ]
then
	mkdir .git
	touch .git/prefs
	mkdir .git/travail
fi

cd .git

. prefs

[ ! -z "$nomComp" ] || nomComp="$nom"
[ ! -z "$PACKAGIST_URI" ] || PACKAGIST_URI=$racineComposer/$nomComp

cd travail
if [ ! -f ../auteurs ]
then
	darcs-to-git ../.. --list-authors | sed -e '1,/^---$/s/^\([^#]\)/#- \1/' > ../auteurs && vi ../auteurs
fi
git checkout master || true
darcs-to-git ../.. --author-map ../auteurs || true
if ! grep -q remote.\*origin .git/config
then
	git remote add origin git@github.com:$moiGitHub/$nom.git
fi
# Y a-t-il de quoi générer une version?
daterVersionComposer
git push --tags -u origin master
curl -X POST -H 'Content-Type: application/json' "https://packagist.org/api/update-package?username=$moiComposer&apiToken=$PACKAGIST_API_TOKEN" -d '{"repository":{"url":"https://packagist.org/packages/'"$PACKAGIST_URI"'"}}'
