#!/bin/sh
set -e
set -x

Delibere() { local s2 ; while [ -h "$s" ] ; do s2="`readlink "$s"`" ; case "$s2" in [^/]*) s2="`dirname "$s"`/$s2" ;; esac ; s="$s2" ; done ; } ; SCRIPTS() { local s="`command -v "$0"`" ; [ -x "$s" -o ! -x "$0" ] || s="$0" ; case "$s" in */bin/*sh) case "`basename "$s"`" in *.*) true ;; *sh) s="$1" ;; esac ;; esac ; case "$s" in [^/]*) local d="`dirname "$s"`" ; s="`cd "$d" ; pwd`/`basename "$s"`" ;; esac ; Delibere ; s="`dirname "$s"`" ; Delibere ; SCRIPTS="$s" ; } ; SCRIPTS

# À FAIRE: s'arrêter sur conflit pour retouche manuelle.

# À FAIRE: gestion des dépendances entre incréments.

# À FAIRE: gérer les renommages de fichiers, voire leur déplacement s'ils étaient initialement dans un dossier au-dessus (donc non pris en compte par le tar). Peut-être par introduction d'une phase manuelle qui permettrait de prendre la main sur le processus automatique, par exemple en darcs addant le fichier (non vu par l'auto) dans son nommage originale, puis court-circuitant le darcs add auto du fichier dans son nommage définitif par un darcs mv manuel.
#   Note 2026: l'ajout de --look-for-moves mitige-t-il?

# À FAIRE: de temps en temps ça plante, une modif n'est pas appliquée et donc l'enregistrement plante en "No changes!". En relançant ça passe (un silo de 180 rustines a planté à deux endroits différents avant de pouvoir se dérouler une troisième fois jusqu'au bout).

# Utilisation: extractiondarcs <destination> <fichier>*
# N.B.: si un des fichiers à reprendre a eu un autre nom, il faut le spécifier sous son ancien et son nouveau nom.

# On peut ensuite supprimer du silo d'origine toute trace du fichier:
# DARCS_ALWAYS_COLOR=0 darcs log scripts/sauvegarde/lnertotal.c scripts/sauvegarde/crc32.c | grep '^patch ' | while read p id ; do darcs obli -a -h $id ; done

T=/tmp/temp.$$
mkdir $T

	case "$1" in -i) interactif=1 ; shift ;; esac
dest="$1"
shift

# Calcul d'où on est par rapport à _darcs.

ici="`pwd`"
descente=
until [ -d "_darcs" ]
do
	descente="`basename "$ici"`/$descente"
	cd ..
	ici="`pwd`"
done
format="`grep darcs- _darcs/format`"
cd "$ici"

# Création des dossiers de travail.

mkdir $T/src
mkdir $T/dst

[ $format = darcs-2 ] || type=--hashed
( cd $T/src && darcs init $type )
( cd $T/dst && darcs init )

# darcs changes pour pipe
dcp()
{
	darcs changes "$@" --xml | awk \
'
/<patch /{
	d = $0;
	gsub(/.* date=['\''"]/, "", d); gsub(/['\''"].*/, "", d);
	print d;
	a = $0;
	gsub(/.* author=['\''"]/, "", a); gsub(/['\''"].*/, "", a);
	print a;
}
/<name>/{ gsub(/[ 	]*<[^>]*>[ 	]*/, ""); print; }
/<comment>/{ sub(/.*<comment>/, ""); dedans = 1; }
/<\/comment>/{ sub(/<\/comment>.*/, ""); dedans = 2; }
/^Ignore-this: /{ next; }
dedans{ print; }
dedans==2{ dedans = 0; }
' \
	| php -r 'foreach(explode("\n", trim(stream_get_contents(STDIN))) as $l) { $ic = iconv("utf-8", "cp1252//IGNORE", $l); if($l == @iconv("cp1252", "utf-8", iconv("cp1252", "utf-8", iconv("utf-8", "cp1252//IGNORE", $ic)))) $l = $ic; echo "$l\n"; }' \
	| php -r 'echo trim(html_entity_decode(stream_get_contents(STDIN), ENT_QUOTES|ENT_HTML5));'
}

pretravail()
{
	case "$interactif" in
		1)
			. "$SCRIPTS/shrc"
			( cd "$ici/$descente" && histo_darcs +"p %d %9h %t" --reverse "$@" ) > $T/boulot
			case "$EDITOR" in "") EDITOR=vi ;; esac
			$EDITOR $T/boulot
			cp $T/boulot /tmp/boulot.extractiondarcs
			;;
	esac
}

travail()
{
	case "$interactif" in
		1)
			awk < $T/boulot \
			'
				function aff() { if(l) print l; }
				/^p / { aff(); $1 = ""; l = $0; next; }
				/^f / { ajout = $3; $0 = l; $2 = $2","ajout; l = $0; next; }
				{ print NR": ligne non reconnue: "$0 > "/dev/stderr"; exit 1; }
				END { aff(); }
			'
			;;
		*)
			( cd "$ici/$descente" && DARCS_ALWAYS_COLOR=0 darcs log "$@" ) | grep -n '^patch ' | sort -nr
			;;
	esac
}

	pretravail
	travail | while read blabla id blibli
do
		IFS=,
		id0=
		for id in $id
		do
			unset IFS
			case "$id0" in "") id0="$id" ;; esac
		echo a | darcs push -h "$id" $T/src
		done
	mv $T/src/_darcs $T/src_darcs
	mv $T/dst/_darcs $T/dst_darcs
	rm -R $T/dst
	mkdir $T/dst
	( cd $T/src/$descente && tar cf - . ) | ( cd $T/dst && tar xf - ) || true
	mv $T/dst_darcs $T/dst/_darcs
	mv $T/src_darcs $T/src/_darcs
		case "$*" in
			"") ( cd $T/dst && darcs add -r . ) || true ;;
			*)
		( cd $T/dst && for f in "$@" ; do [ ! -e "$f" ] || darcs add -r "$f" ; done ) || true
		esac
		( cd $T/src && dcp -h "$id0" ) | ( cd $T/dst && darcs record --look-for-moves -a --pipe )
done

rm -Rf "$dest" # Euh est-ce une bonne idée? Ne devrait-on pas demander un -f pour ce faire?
mv $T/dst "$dest"

rm -R $T
