#!/bin/sh
# À inclure dans son .shrc

dl()
{
	# darcs log embarque son propre pagineur, malheureusement il ne lui transmet pas les 'q' pour quitter.
	darcs log "$@" | less
}

dw()
{
	DARCS_ALWAYS_COLOR=1 darcs w "$@" | less -RFX
}

# Darcs Whatsnew Récents.
dwr()
{
	local njours=10
	case "$1" in
		*[^0-9]*|"") true ;;
		*) njours="$1" ; shift ;;
	esac
	dw "$@" `find . -mindepth 1 -not -path "./_darcs/*" -not -path "./.git/*" -mtime -$njours | grep -v util.loca`
}

#- Projets ---------------------------------------------------------------------
# Fonctionnement dans le cadre de rcs/shrc.

testi_darcs()
{
	[ -d "$1/_darcs" ] || return
	
	local init
	for init in $DANSPROJET_TESTI_DARCS
	do
		$init "$1"
	done
}

DANSPROJET_TESTI="$DANSPROJET_TESTI testi_darcs"
DANSPROJET_TESTI_DARCS=

#- Bas-niveau ------------------------------------------------------------------

histo_darcs()
{
	local format='%d %D # %t'
	while [ $# -gt 0 ]
	do
		case "$1" in
			+*) format="`echo "$1" | cut -c 2-`" ;;
			*) break ;;
		esac
		shift
	done
	
	darcs log --xml-output "$@" | awk \
'
BEGIN{ format = "'"$format"'"; }
/<patch/{
	match($0, / date=["'\''][^"'\'']*/); dateIso = substr($0, RSTART + 7, RLENGTH - 7);
	match($0, / local_date=["'\''][^"'\'']*/); dateLocale = substr($0, RSTART + 13, RLENGTH - 13);
}
/<name>/{
	sub(/.*<name>/, "");
	sub(/<\/name>.*/, "");
	gsub(/&amp;/, "\\&");
	gsub(/&apos;/, "'\''");
	gsub(/&gt;/, ">");
	gsub(/&lt;/, "<");
	gsub(/&quot;/, "\"");
	titre = $0;
}
/<\/patch>/{
	sortie = format;
	gsub("%d", dateIso, sortie);
	gsub("%D", dateLocale, sortie);
	gsub("%t", titre, sortie);
	print sortie;
}
'
}
