#!/bin/sh
# Copyright (c) 2023 Guillaume Outters
# 
# Permission is hereby granted, free of charge, to any person obtaining a copy
# of this software and associated documentation files (the "Software"), to deal
# in the Software without restriction, including without limitation the rights
# to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
# copies of the Software, and to permit persons to whom the Software is
# furnished to do so, subject to the following conditions:
# 
# The above copyright notice and this permission notice shall be included in
# all copies or substantial portions of the Software.
# 
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT.  IN NO EVENT SHALL THE
# AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
# OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
# SOFTWARE.

# Bute un processus Oracle après sélection.

sqlo() { … }
ssho() { … }

sqlo "
	select
		'[32m'||to_char(a.sql_exec_start, 'YYYY-MM-DD HH24:MI:SS')||'[0m' debut, a.process pid, '[31m'||spid||'[0m' spid, a.sid, a.serial#, a.username,b.sql_id, cast(substr(b.sql_fulltext, 1, 4000) as varchar2(4000)),
	    a.*
	from v\\\$session a, v\\\$sql b, v\\\$process p
	where a.sql_id = b.sql_id and a.status = 'ACTIVE' and a.username != 'SYS'
	and p.addr = a.paddr
	order by sql_exec_start, a.process
" | less
printf "Lequel buter? " ; read cible
ssho "kill $cible ; sleep 20 ; kill -9 $cible"
