#!/bin/bash
# Copyright (c) 2005 Guillaume Outters
# 
# Permission is hereby granted, free of charge, to any person obtaining a copy
# of this software and associated documentation files (the "Software"), to deal
# in the Software without restriction, including without limitation the rights
# to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
# copies of the Software, and to permit persons to whom the Software is
# furnished to do so, subject to the following conditions:
# 
# The above copyright notice and this permission notice shall be included in
# all copies or substantial portions of the Software.
# 
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT.  IN NO EVENT SHALL THE
# AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
# OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
# SOFTWARE.

auSecours()
{
	nom=`basename "$0"`
	cat >&2 << TERMINE
# $nom
# Remlace dans une liste alboretum les dates par celles d'une seconde liste
# © 2005 Guillaume Outters

Utilisation: $nom <liste à données> <liste à dates>
TERMINE
	exit 1
}

analyserParametres()
{
	DONNEES=
	DATES=
	while [ $# -gt 0 ] ; do
		case "$1" in
			*)
				for i in DONNEES DATES ; do
					if eval test -z \$$i ; then
						eval $i=\""$1"\"
						break
					fi
				done
				;;
		esac
		shift
	done
	return 0
}

analyserParametres "$@"
[ -z "$DONNEES" -o -z "$DATES" ] && auSecours

mkdir /tmp/$$

grep '<date>' < "$DATES" > /tmp/$$/dates
awk '{oui=1}/<date>/{oui=0;system("read ligne <&3 ; echo \"		$ligne\"")}{if(oui){print $0}}' < "$DONNEES" 3< /tmp/$$/dates

rm -R /tmp/$$
