#!/bin/sh

# Transcrire l'Audio en Texte

contexte="Guillaume Outters a bossé chez Bouygues Télécom Entreprises, comme SN3 Transverse, sur les IMEI, les MSISDN, avec la MOE."

tourner()
{
	# Analyse des paramètres.
	
	while [ $# -gt 0 ]
	do
	case "$1" in
			*.flac|*.mp3|*.opus|*.wav)
				son="$1"
				m="`echo "$1" | sed -E -e 's#\.[^.]{3,4}$##'`"
				;;
			*) break ;;
	esac
		shift
	done
	
	case "$m" in "")
m=/tmp/tat.`date +%Y%m%d.%H%M%S`
	;; esac
	case "$son" in "")
		son="$m.mp3"
	;; esac
	
	# C'est parti!
	
	faire "$@"
}

aff()
{
	awk \
	'
		BEGIN { r = ""; n = 0; }
		/^$/ { print; next; }
		{ t = ""; }
		/^\[/ {
			match($0, /\] */);
			t = substr($0, RSTART + RLENGTH);
			$0 = substr($0, 1, RSTART + RLENGTH - 1);
			gsub(/\.\.\./, "…", t);
			
			r = r""t;
			while(match(r, /[.!?] */))
			{
				tout[++n] = substr(r, 1, RSTART);
				print tout[n] >> "'"$m"'.txt";
				r = substr(r, RSTART + RLENGTH);
			}
			if(r) r = r" ";
		}
		{ print "[90m"$0"[0m"t; }
		END {
			if(r)
			{
				tout[++n] = r;
				print tout[n] >> "'"$m"'.txt";
			}
			print "";
			for(i = 0; ++i <= n;) print tout[i];
		}
	'
}

faire()
{
	[ -f "$son" ] ||
	sox -t oss /dev/dsp1 $son || true
	case "$son" in
		*.mp3|*.wav) true ;;
		*) ffmpeg -i "$son" "$son.wav" ; son="$son.wav" ;;
	esac
	whisper-cli -m ~/local/share/whisper/models/ggml-small.bin --language French --prompt "$contexte" "$@" $son 2>&1 | aff
	echo "($son, $m.txt)"
case "$WAYLAND_DISPLAY" in ?*)
	wl-copy -p < $m.txt
esac
}

# À FAIRE: trouver tout seul le modèle

tourner "$@"
